import "./globals.css";
import { artin, iranSans, iranYekan } from "../font";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="FA-IR" dir="rtl">
      <body
        className={`${iranYekan.className} bg-black text-white dark:bg-zinc-900 dark:text-white relative transition-colors`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
